apiVersion: v1
entries:
  ocpp:
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2021-08-28T23:04:26.133842916Z"
    description: A Helm chart for Kubernetes
    digest: 9960a0a0ca58c8db10368020feccc08ed90f22df191051f80030231c3f6b7106
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.18.tgz
    version: 0.0.18
  - apiVersion: v2
    appVersion: 0.0.17
    created: "2021-08-28T21:45:07.931525933Z"
    description: A Helm chart for Kubernetes
    digest: 23ee495d7ca34b7b319fdcca6668a02340a16a74da7afe50c54c7bd1b2d9bb34
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.17.tgz
    version: 0.0.17
  - apiVersion: v2
    appVersion: 0.0.16
    created: "2021-08-28T21:19:31.819452054Z"
    description: A Helm chart for Kubernetes
    digest: 5f1b0d158cfaf295d445fef908b5f2120cffb3f2be76f2f01c412e22c1269145
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.16.tgz
    version: 0.0.16
  - apiVersion: v2
    appVersion: 0.0.15
    created: "2021-08-28T20:37:49.540034672Z"
    description: A Helm chart for Kubernetes
    digest: 2e2a1f217b2465a4a42c3f5d963fc6041591e5ef75dcc179166e9a2a60d8b137
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.15.tgz
    version: 0.0.15
  - apiVersion: v2
    appVersion: _VERSION_RELEASE_
    created: "2021-08-28T20:23:45.773677459Z"
    description: A Helm chart for Kubernetes
    digest: ffe5398c0810b6de8a77bb929d7efc235b43df729adbe07bb42ed93c8c613d18
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.14.tgz
    version: 0.0.14
  - apiVersion: v2
    appVersion: _VERSION_RELEASE_
    created: "2021-08-28T19:13:30.321487982Z"
    description: A Helm chart for Kubernetes
    digest: 4388cbefda4def466a7f3dd57880be4bab17a74c2003b062c7fc2e119d0a75d0
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.13.tgz
    version: 0.0.13
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-28T18:09:04.46521136Z"
    description: A Helm chart for Kubernetes
    digest: 967fbb48c00719dcb5360ea2430ea0d0d66f942b0889e810aa7326f94d212d9d
    name: ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.12.tgz
    version: 0.0.12
generated: "2021-08-28T23:04:26.133418108Z"
